### ISSUE TITLE
Would be nice to be able to see status of the queue

### ISSUE THREAD

**Issue by jacksonj04** [everypolitician/commons-api#8]
Some form of indication as to the status of the refresh queue - how many items are in it, how long they've been there and so-on.

As an added bonus, would be nice for any given page to see if there is a refresh already pending, and if so to disable the "refresh" button.

**Comment by alexsdutton** [comment]
For queue length, we probably will have to do something along the lines of https://stackoverflow.com/questions/17863626/retrieve-queue-length-with-celery-rabbitmq-django/39230080#39230080 using the RabbitMQ management API, as celery itself is blind to the number of not-yet-prefetched items in a queue. `flower` can show pending tasks, but it does that by observing events in real-time, which I don't think we want.

For the added bonus, I think we can do this by enabling a celery results backend (e.g. `django-celery-results`), and then storing the task ID on the model. The view can then use `AsyncResult(task_id)` to get the state, and disable the button accordingly.
